export const METADATA = [
  {
    id: 1,
    name: "Jamie",
    email: "Jamie123@123.com",
    phone: 123456789,
    website: "jamie.org",
  },
  {
    id: 2,
    name: "Alice",
    email: "alice@example.com",
    phone: 987654321,
    website: "alice.com",
  },
  {
    id: 3,
    name: "Bob",
    email: "bob@example.com",
    phone: 555555555,
    website: "bob.net",
  },
  {
    id: 4,
    name: "Eva",
    email: "eva@example.com",
    phone: 777777777,
    website: "eva.org",
  },
  {
    id: 5,
    name: "David",
    email: "david@example.com",
    phone: 111111111,
    website: "david.net",
  },
  {
    id: 6,
    name: "Emma",
    email: "emma@example.com",
    phone: 222222222,
    website: "emma.org",
  },
  {
    id: 7,
    name: "Michael",
    email: "michael@example.com",
    phone: 333333333,
    website: "michael.com",
  },
  {
    id: 8,
    name: "Olivia",
    email: "olivia@example.com",
    phone: 444444444,
    website: "olivia.net",
  },
  {
    id: 9,
    name: "Liam",
    email: "liam@example.com",
    phone: 888888888,
    website: "liam.org",
  },
  {
    id: 10,
    name: "Sophia",
    email: "sophia@example.com",
    phone: 666666666,
    website: "sophia.com",
  },
  {
    id: 11,
    name: "Noah",
    email: "noah@example.com",
    phone: 999999999,
    website: "noah.net",
  },
  {
    id: 12,
    name: "Ava",
    email: "ava@example.com",
    phone: 121212121,
    website: "ava.org",
  },
  {
    id: 13,
    name: "James",
    email: "james@example.com",
    phone: 343434343,
    website: "james.com",
  },
  {
    id: 14,
    name: "Mia",
    email: "mia@example.com",
    phone: 565656565,
    website: "mia.net",
  },
  {
    id: 15,
    name: "Alexander",
    email: "alexander@example.com",
    phone: 787878787,
    website: "alexander.org",
  },
  {
    id: 16,
    name: "Charlotte",
    email: "charlotte@example.com",
    phone: 989898989,
    website: "charlotte.com",
  },
  {
    id: 17,
    name: "Daniel",
    email: "daniel@example.com",
    phone: 676767676,
    website: "daniel.net",
  },
  {
    id: 18,
    name: "Emily",
    email: "emily@example.com",
    phone: 454545454,
    website: "emily.org",
  },
  {
    id: 19,
    name: "William",
    email: "william@example.com",
    phone: 232323232,
    website: "william.com",
  },
  {
    id: 20,
    name: "Grace",
    email: "grace@example.com",
    phone: 121212121,
    website: "grace.net",
  },
  {
    id: 21,
    name: "Lily",
    email: "lily@example.com",
    phone: 11112222333,
    website: "lily.org",
  },
  {
    id: 22,
    name: "Lucas",
    email: "lucas@example.com",
    phone: 44445555666,
    website: "lucas.net",
  },
  {
    id: 23,
    name: "Sophie",
    email: "sophie@example.com",
    phone: 77778888999,
    website: "sophie.com",
  },
  {
    id: 24,
    name: "Henry",
    email: "henry@example.com",
    phone: 12344321567,
    website: "henry.org",
  },
  {
    id: 25,
    name: "Aiden",
    email: "aiden@example.com",
    phone: 9876554321,
    website: "aiden.net",
  },
  {
    id: 26,
    name: "Emma",
    email: "emma@example.com",
    phone: 9876123456,
    website: "emma.com",
  },
  {
    id: 27,
    name: "Daniel",
    email: "daniel@example.com",
    phone: 1111987654,
    website: "daniel.org",
  },
  {
    id: 28,
    name: "Mia",
    email: "mia@example.com",
    phone: 9999888777,
    website: "mia.net",
  },
  {
    id: 29,
    name: "Oliver",
    email: "oliver@example.com",
    phone: 1111222333,
    website: "oliver.com",
  },
  {
    id: 30,
    name: "Ava",
    email: "ava@example.com",
    phone: 4444555666,
    website: "ava.org",
  },
  {
    id: 31,
    name: "Ethan",
    email: "ethan@example.com",
    phone: 7777888999,
    website: "ethan.net",
  },
  {
    id: 32,
    name: "Chloe",
    email: "chloe@example.com",
    phone: 3333444555,
    website: "chloe.com",
  },
  {
    id: 33,
    name: "William",
    email: "william@example.com",
    phone: 2222333444,
    website: "william.org",
  },
  {
    id: 34,
    name: "Aria",
    email: "aria@example.com",
    phone: 5555666777,
    website: "aria.net",
  },
  {
    id: 35,
    name: "James",
    email: "james@example.com",
    phone: 8888999111,
    website: "james.com",
  },
  {
    id: 36,
    name: "Abigail",
    email: "abigail@example.com",
    phone: 1212121212,
    website: "abigail.org",
  },
  {
    id: 37,
    name: "Liam",
    email: "liam@example.com",
    phone: 3434343434,
    website: "liam.net",
  },
  {
    id: 38,
    name: "Charlotte",
    email: "charlotte@example.com",
    phone: 5656565656,
    website: "charlotte.com",
  },
  {
    id: 39,
    name: "Noah",
    email: "noah@example.com",
    phone: 7878787878,
    website: "noah.org",
  },
  {
    id: 40,
    name: "Ella",
    email: "ella@example.com",
    phone: 9999999999,
    website: "ella.net",
  },
  {
    id: 41,
    name: "Liam",
    email: "liam@example.com",
    phone: 1234123412,
    website: "liam.org",
  },
  {
    id: 42,
    name: "Ava",
    email: "ava@example.com",
    phone: 5678567856,
    website: "ava.com",
  },
  {
    id: 43,
    name: "Oliver",
    email: "oliver@example.com",
    phone: 9090909090,
    website: "oliver.net",
  },
  {
    id: 44,
    name: "Amelia",
    email: "amelia@example.com",
    phone: 1212121212,
    website: "amelia.org",
  },
  {
    id: 45,
    name: "Ethan",
    email: "ethan@example.com",
    phone: 3434343434,
    website: "ethan.com",
  },
  {
    id: 46,
    name: "Emma",
    email: "emma@example.com",
    phone: 5656565656,
    website: "emma.net",
  },
  {
    id: 47,
    name: "James",
    email: "james@example.com",
    phone: 7878787878,
    website: "james.org",
  },
  {
    id: 48,
    name: "Sophia",
    email: "sophia@example.com",
    phone: 9898989898,
    website: "sophia.com",
  },
  {
    id: 49,
    name: "Lucas",
    email: "lucas@example.com",
    phone: 11112222333,
    website: "lucas.net",
  },
  {
    id: 50,
    name: "Aria",
    email: "aria@example.com",
    phone: 44445555666,
    website: "aria.org",
  },
  {
    id: 51,
    name: "Mia",
    email: "mia@example.com",
    phone: 77778888999,
    website: "mia.com",
  },
  {
    id: 52,
    name: "Noah",
    email: "noah@example.com",
    phone: 12344321567,
    website: "noah.net",
  },
  {
    id: 53,
    name: "Emma",
    email: "emma@example.com",
    phone: 9876554321,
    website: "emma.org",
  },
  {
    id: 54,
    name: "Liam",
    email: "liam@example.com",
    phone: 1111111111,
    website: "liam.com",
  },
  {
    id: 55,
    name: "Ava",
    email: "ava@example.com",
    phone: 2222222222,
    website: "ava.net",
  },
  {
    id: 56,
    name: "Oliver",
    email: "oliver@example.com",
    phone: 3333333333,
    website: "oliver.org",
  },
  {
    id: 57,
    name: "Amelia",
    email: "amelia@example.com",
    phone: 4444444444,
    website: "amelia.com",
  },
  {
    id: 58,
    name: "Ethan",
    email: "ethan@example.com",
    phone: 5555555555,
    website: "ethan.net",
  },
  {
    id: 59,
    name: "Sophia",
    email: "sophia@example.com",
    phone: 6666666666,
    website: "sophia.org",
  },
  {
    id: 60,
    name: "Lucas",
    email: "lucas@example.com",
    phone: 7777777777,
    website: "lucas.com",
  },
  {
    id: 61,
    name: "Aria",
    email: "aria@example.com",
    phone: 8888888888,
    website: "aria.net",
  },
  {
    id: 62,
    name: "Mia",
    email: "mia@example.com",
    phone: 9999999999,
    website: "mia.org",
  },
  {
    id: 63,
    name: "Noah",
    email: "noah@example.com",
    phone: 1111111111,
    website: "noah.com",
  },
];
